### ISSUE TITLE
wiimote/wiitrack: Build conditionally depending on whether cwiid is available

### ISSUE THREAD

**Issue by ethus3h** [ethus3h/compiz-plugins-community#23]
Not sure how to do this, I need to read up on doing dependency checking in configure.ac / Makefiles...

**Comment by Eignar17** [comment]
my code is disaster  sorry :(

**Comment by Eignar17** [comment]
in to wiimote is problem is prompt  view NEWS.md

**Comment by ethus3h** [comment]
Your code is fine! I just don't know autoconf well enough yet to have the buildsystem disable the plugins automatically when the dependencies aren't already installed.

**Comment by Eignar17** [comment]
ok check new code

**Comment by ethus3h** [comment]
It'll be a bit before I can test, sorry — have a big system update to get done first

**Comment by Eignar17** [comment]
@ethus3h test all actual plugins and my update code griswold sound to compiz-plugins-community

**Comment by ethus3h** [comment]
ooh! Sweet, thanks for fixing this @Eignar17 ! :grin:

**Comment by Eignar17** [comment]
all right
