### ISSUE TITLE
port to gitlab

### ISSUE THREAD

**Issue by Eignar17** [ethus3h/compiz-plugins-community#26]
@ethus3h  view project compiz-reloaded
https://gitlab.com/compiz

**Comment by ethus3h** [comment]
I've been considering that. Their Web site is unusably buggy for me, though. GitHub's is far from perfect, but at least it works.

**Comment by ethus3h** [comment]
I've at least gotten the repository available at GitLab: https://gitlab.com/ethus3h/compiz-plugins-community :)

I think I'm starting to understand GitLab somewhat, maybe. :deciduous_tree:

That doesn't include an issue tracker, though; I don't have a good solution yet for syncing the issues.

This is at least a step towards having it available there, anyway. Sorry it's taken so long. Enjoy! :)

**Comment by Eignar17** [comment]
ok
