### ISSUE TITLE
error rubik

### ISSUE THREAD

**Issue by Eignar17** [ethus3h/compiz-plugins-community#6]
compiz (rubik) - Error: InitObject failed
compiz (core) - Error: Couldn't activate plugin 'rubik'
compiz (core) - Error: Plugin 'core' has ABI version '20091102', expected ABI version '20080424'.

compiz (rubik) - Error: InitObject failed
compiz (core) - Error: Couldn't activate plugin 'rubik'

**Comment by ethus3h** [comment]
Why closed it? Is this problem solved? I thought I reproduced it earlier, but maybe that was a different crash...

Haven't had time to look into it yet anyway, heh. Mad busy ;P

**Comment by Eignar17** [comment]
conflict plugin in classic vercion in my pc is new problem plugin not work fine

**Comment by Eignar17** [comment]
error view windows and desktop nictitate


![pantallazo-2017-09-20 16-59-31](https://user-images.githubusercontent.com/8561550/30669818-65fa5a5c-9e25-11e7-9a21-829a5cf1febf.png)
![pantallazo-2017-09-20 16-59-56](https://user-images.githubusercontent.com/8561550/30669819-66134c7e-9e25-11e7-9aa4-acf0ca4d506d.png)
